TMDB/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('actors/', include('actress.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('contact/', views.contact_us, name='contact'),
    path('thanks/', views.submit_message, name='messagesent'),
    path('<int:pk>/watchlist', views.add_watch_list, name='watchlist'),
    path('watchlist/', views.watch_list_func, name='watchlist_func'),
    path('<int:pk>/delete/', views.delete_watch_list, name='delete'),
]

movies/urls.py
from django.urls import path, include
from movies import views


urlpatterns = [
    path('top/', views.TopMoviesListView.as_view(), name='all_movies'),
    path('<int:pk>/', views.MoviesDetailView.as_view(), name='detailed_movie'),
    path('<int:pk>/voting/', views.voting, name='voting'),
    path('<int:pk>/comments/', views.add_comment, name='comment'),
    path('latest/', views.NewMoviesListView.as_view(), name='latest'),
    path('actors/', include('actress.urls')),
    path('result/', views.search_movie, name='result'),
]

movies/models.py
from django.db import models
from django.contrib.auth.models import User
from actress.models import Actor
from django.utils import timezone


# Create your models here.
class Movies(models.Model):
    title = models.CharField(max_length=256)
    summary = models.TextField()
    release_date = models.DateField()
    rate = models.FloatField(default=0)
    cast_list = models.ManyToManyField(Actor, through='ActorMovie')
    icon = models.ImageField(upload_to='images/', null=True)
    image = models.ImageField(upload_to='images/', null=True)
    genre = models.CharField(max_length=256)
    director = models.CharField(max_length=256)
    rate_counter = models.PositiveIntegerField(default=1)
    rater = models.ManyToManyField(User, through='UserRater', null=True, blank=True)

    def summary_card_body(self):
        return self.summary[:70] + '...'

    def __str__(self):
        return self.title

    def cast_list_func(self):
        movies_actors = Actor.objects.filter(actors_movies__movie_id=self.pk)
        return movies_actors

    def comment_func(self):
        return self.comments.filter(movie_id=self.pk)


class ActorMovie(models.Model):
    movie = models.ForeignKey(Movies, related_name='casts', on_delete=models.CASCADE)
    actor = models.ForeignKey(Actor, related_name='actors_movies', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.actor) + ' - ' + str(self.movie)


class UserRater(models.Model):
    user_rater = models.ForeignKey(User, related_name='rates', on_delete=models.CASCADE)
    movie_rated = models.ForeignKey(Movies, related_name='rated', on_delete=models.CASCADE)
    user_rate = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.user_rater) + ' - ' + str(self.movie_rated)


class Comment(models.Model):
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cm_author')
    cm_text = models.TextField()
    cm_date = models.DateTimeField(default=timezone.now)

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from movies import models
from django.views.generic import ListView, DetailView


# Create your views here.
def home_page(request):
    page_title = 'Home'
    movie_slid_bar = models.Movies.objects.filter(rate__gt=7)[:3]
    movies_top_rated = models.Movies.objects.filter(rate__gte=8).order_by('-rate')[:12]
    new_movies = models.Movies.objects.filter(release_date__year__gte='2019')[:6]
    famous_actors = models.Actor.objects.filter()[:6]
    return render(request, 'movies/home.html', {'movie_slid_bar': movie_slid_bar,
                                                'movies_top_rated': movies_top_rated,
                                                'new_movies': new_movies,
                                                'famous_actors': famous_actors,
                                                'page_title': page_title})


class TopMoviesListView(ListView):
    template_name = 'movies/all_movies.html'
    model = models.Movies
    paginate_by = 10

    def get_queryset(self):
        return models.Movies.objects.filter(rate__gte=8).order_by('-rate')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Top Movies'
        return context


class NewMoviesListView(ListView):
    template_name = 'movies/new_movies.html'
    model = models.Movies
    paginate_by = 10

    def get_queryset(self):
        return models.Movies.objects.filter(release_date__year__gte=2019).order_by('-rate')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'New Movies'
        return context


class MoviesDetailView(DetailView):
    model = models.Movies
    template_name = 'movies/detailed_movie.html'

    def get_context_data(self, **kwargs):
        related = self.object.genre.split(',')[0]
        context = super().get_context_data(**kwargs)
        context['related'] = models.Movies.objects.filter(genre__contains=related).filter(rate__gte=8).exclude(
            title=self.object.title)[:6]
        context['listed'] = models.Movies.objects.filter(movie_on_list__user_who_add_to_list_id=self.request.user.pk)
        context['rated'] = models.Movies.objects.filter(rated__user_rater_id=self.request.user.pk)
        context['page_title'] = self.object.title
        return context


def voting(request, pk):
    if request.method == 'POST':
        movie = get_object_or_404(models.Movies, pk=pk)
        rater = models.UserRater.objects.create(movie_rated=movie,
                                                user_rater=request.user,
                                                user_rate=int(request.POST['vote_value']))
        rater.save()
        movie.rate_counter += 1
        movie.rate = (movie.rate + int(request.POST['vote_value'])) / movie.rate_counter
        movie.save()
        return redirect('/movies/' + str(pk))
    else:
        return redirect('/movies/' + str(pk))


def add_comment(request, pk):
    if request.method == 'POST':
        movie = get_object_or_404(models.Movies, pk=pk)
        user = request.user
        comment = models.Comment.objects.create(movie=movie, author=user,
                                                cm_text=request.POST['cm-text'])
        comment.save()
        return redirect('/movies/' + str(pk))
    else:
        return redirect('/movies/' + str(pk))


def search_movie(request):
    if request.method == 'POST':
        search_for = request.POST['search-for']
        search_results = models.Movies.objects.filter(title__icontains=search_for)
        page_title = 'Search Results for: ' + request.POST['search-for']
        return render(request, 'movies/search_result.html', {'search_results': search_results,
                                                             'search_for': search_for,
                                                             'page_title': page_title})

movies/templates/movies/all_movies.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>
        a:hover{
            color: blue;
            text-decoration: none;
        }
        span.stars, span.stars span {
            display: block;
            background: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star-o-white.svg) 0 0 repeat-x;
            width: 120px; /* width of a star multiplied by 5 */
            height: 12px; /* the height of the star */
            background-size: 12px 12px;
            filter: drop-shadow(0px 0px 0px #444);
        }

        span.stars span {
            background-position: 0 0;
            background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star.svg);
        }

        /*PEN STYLES*/
        * {
            box-sizing: border-box;
        }

        body {
            background: #f1f1f1;
        }

        .blog-card {
            display: -webkit-box;
            display: flex;
            -webkit-box-orient: vertical;
            -webkit-box-direction: normal;
            flex-direction: column;
            box-shadow: 0 3px 7px -1px rgba(0, 0, 0, 0.1);
            margin: auto auto 1.6%;
            background: #fff;
            line-height: 1.4;
            font-family: sans-serif;
            border-radius: 5px;
            overflow: hidden;
            z-index: 0;
            width: 100%;
        }

        .blog-card a {
            color: inherit;
        }

        .blog-card a:hover {
            color: #4a30d6;
        }

        .blog-card:hover .photo {
            -webkit-transform: scale(1.3) rotate(3deg);
            transform: scale(1.3) rotate(3deg);
        }

        .blog-card .meta {
            position: relative;
            z-index: 0;
            height: 320px;
        }

        .blog-card .photo {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            background-size: cover;
            background-position: center;
            -webkit-transition: -webkit-transform .2s;
            transition: -webkit-transform .2s;
            transition: transform .2s;
            transition: transform .2s, -webkit-transform .2s;
        }

        .blog-card .details,
        .blog-card .details ul {
        {#margin: auto;#} padding: 0;
            list-style: none;
        }

        .blog-card .details {
            position: absolute;
            top: 0;
            bottom: 0;
            left: -100%;
            margin: auto;
            -webkit-transition: left .2s;
            transition: left .2s;
            background: rgba(0, 0, 0, 0.6);
            color: #fff;
            padding: 10px;
            width: 100%;
            font-size: .9rem;
        }

        .blog-card .details a {
            -webkit-text-decoration: dotted underline;
            text-decoration: dotted underline;
        }

        .blog-card .details ul li {
            display: inline-block;
        }

        .blog-card .details .author:before {
            font-family: FontAwesome;
            margin-right: 10px;
            content: "\f007";
        }

        .blog-card .details .date:before {
            font-family: FontAwesome;
            margin-right: 10px;
            content: "\f133";
        }

        .blog-card .details .tags ul:before {
            font-family: FontAwesome;
            content: "\f02b";
            margin-right: 10px;
        }

        .blog-card .details .tags li {
            margin-right: 2px;
        }

        .blog-card .details .tags li:first-child {
            margin-left: -4px;
        }

        .blog-card .description {
            padding: 1rem;
            background: #fff;
            position: relative;
            z-index: 1;
        }

        .blog-card .description h1,
        .blog-card .description h2 {
            font-family: Poppins, sans-serif;
        }

        .blog-card .description h1 {
            line-height: 1;
            margin: 0;
            font-size: 1.7rem;
        }

        .blog-card .description h2 {
            font-size: 1rem;
            font-weight: 300;
            text-transform: uppercase;
            color: #a2a2a2;
            margin-top: 5px;
        }

        .blog-card .description .read-more {
            text-align: right;
        {#margin-top: 10%;#}
        }

        .blog-card .description .read-more a {
            color: #4a72d6;
            display: inline-block;
            position: relative;
        }

        .blog-card .description .read-more a:after {
        {#content: "\f061";#} font-family: FontAwesome;
            margin-left: -10px;
            opacity: 0;
            vertical-align: middle;
            -webkit-transition: margin .3s, opacity .3s;
            transition: margin .3s, opacity .3s;
        }

        .blog-card .description .read-more a:hover:after {
            margin-left: 5px;
            opacity: 1;
        }

        .blog-card p {
            position: relative;
            margin: 1rem 0 0;
        }

        .blog-card p:first-of-type {
            margin-top: 1.25rem;
        }

        .blog-card p:first-of-type:before {
            content: "";
            position: absolute;
            height: 5px;
            background: #5ad67d;
            width: 35px;
            top: -0.75rem;
            border-radius: 3px;
        }

        .blog-card:hover .details {
            left: 0%;
        }

        @media (min-width: 992px) {
            .blog-card {
                -webkit-box-orient: horizontal;
                -webkit-box-direction: normal;
                flex-direction: row;
                max-width: 100%;
            }

            .blog-card .meta {
                flex-basis: 40%;

            }

            .blog-card .description {
                flex-basis: 60%;
            }

            .blog-card .description:before {
                -webkit-transform: skewX(-3deg);
                transform: skewX(-3deg);
                content: "";
                background: #fff;
                width: 30px;
                position: absolute;
                left: -10px;
                top: 0;
                bottom: 0;
                z-index: -1;
            }

            .blog-card.alt {
                -webkit-box-orient: horizontal;
                -webkit-box-direction: reverse;
                flex-direction: row-reverse;
            }

            .blog-card.alt .description:before {
                left: inherit;
                right: -10px;
                -webkit-transform: skew(3deg);
                transform: skew(3deg);
            }

            .blog-card.alt .details {
                padding-left: 25px;
            }
        }

    </style>

    <div class="container">
        <div class="row">
            {% for movie in movies_list %}
                <div class="blog-card mt-4">
                    <div class="meta">
                        <div class="photo"
                             style="background-image: url({{ movie.image.url }});"></div>
                        <ul class="details">
                            <span>{{ movie.director }}</span>
                            <div>
                                <span>{{ movie.release_date|date:'Y' }}</span>
                            </div>
                        </ul>
                    </div>
                    <div class="description">
                        <h1>{{ movie.title }}</h1>
                        <h2>{{ movie.genre }}</h2>
                        <p>{{ movie.summary }}</p>
                        <div style="align-self: flex-start" class="link-decor">
                            <p>Actors: {% for item in movie.cast_list_func %}
                                {% if forloop.counter == movie.cast_list_func|length %}
                                    <a href="{% url 'actor_detail' item.id %}">{{ item }}</a>
                                {% else %}
                                    <a href="{% url 'actor_detail' item.id %}">{{ item }}</a>,
                                {% endif %}
                            {% endfor %}
                            </p>
                        </div>
                        <div style="align-self: flex-start">
                            <p><span class="stars">{{ movie.rate }}</span></p>
                            <p>{{ movie.rate|stringformat:'.1f' }}/10</p>
                        </div>
                        <p class="read-more">
                            <a href="{% url 'detailed_movie' movie.id %}">Read More</a>
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                    <li class="page-item active"><a class="page-link"
                                                    href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
{% endblock %}

movies/templates/movies/detailed_movie.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>

        .link-decore a:link {
            color: black;
        }

        .link-decore a:visited {
            color: black;
        }

        .link-decore a:hover {
            color: black;
            text-decoration: none;
        }

        .actor-cls a:hover {
            color: #4a72d6;
            text-decoration: none;
        }

        .actor-cls a:link {
            color: black;
        }

        .actor-cls a:visited {
            color: black;
        }

        span.stars, span.stars span {
            display: block;
            background: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star-o-white.svg) 0 0 repeat-x;
            width: 120px; /* width of a star multiplied by 5 */
            height: 12px; /* the height of the star */
            background-size: 12px 12px;
            filter: drop-shadow(0px 0px 0px #444);
        }

        span.stars span {
            background-position: 0 0;
            background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star.svg);
        }

        body, html {
            height: 100%;
        }

        .hero-image {
            /* Use "linear-gradient" to add a darken background effect to the image (photographer.jpg). This will make the text easier to read */
            background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('{{ movies.image.url }}');

            /* Set a specific height */
            height: 50%;

            /* Position and center the image to scale nicely on all screens */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            position: relative;
            margin-right: 10%;
            margin-left: 10%;
        }

        /* Place text in the middle of the image */
        .hero-text {
            text-align: center;
            position: relative;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: white;
        }

        .movie-detail {
            margin-right: 10%;
            margin-left: 10%;
        }
    </style>


    <div class="hero-image mt-2">
        <div class="hero-text">
            <h1>{{ movies.title }}</h1>
            <p>{{ movies.release_date|date:'Y' }}</p>
        </div>
    </div>
    <div class="card movie-detail mb-2">
        <h5 class="card-header">{{ movies.genre }}</h5>
        <div class="card-body actor-cls">
            <h5 class="card-title">Directed by: {{ movies.director }}</h5>
            <p class="card-text">{{ movies.summary }}</p>
            <p>Actors:
                {% for item in movies.cast_list_func %}
                    {% if forloop.counter == movies.cast_list_func|length %}
                        <a href="{% url 'actor_detail' item.id %}">{{ item }}</a>
                    {% else %}
                        <a href="{% url 'actor_detail' item.id %}">{{ item }}</a>,
                    {% endif %}
                {% endfor %}
            </p>
            <p>{{ movies.rate|stringformat:'.1f' }}/10 from {{ movies.rate_counter }} votes</p>
            {% if user.is_authenticated %}
                {% if movies in rated %}
                    <p>You rated before</p>
                {% else %}
                    <form class="float-left" method="post" action="{% url 'voting' movies.id %}">
                        {% csrf_token %}
                        <label for="cars" style="font-size: large">Your Vote: </label>
                        <select id="cars" class="btn btn-warning btn-large" name="vote_value">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        <input type="submit" value="Submit" class="btn btn-primary btn-large">
                    </form>
                {% endif %}
                <form method="post" action="{% url 'accounts:watchlist' movies.id %}">
                    {% csrf_token %}
                    <input {% if movies in listed%}
                        disabled class="float-right btn btn-danger"
                        value="Marked"
                    {% else %}
                        class="float-right btn btn-outline-danger"
                        value="Watch List"
                    {% endif %} type="submit">
                </form>
            {% endif %}
        </div>
    </div>

    <div class="container">
        <h4 class="mt-4">Related Movies</h4>
        <hr class="hr-class">
    </div>

    <div class="container mx-auto">
        <div class="row">
            {% for item in related %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-2 mb-3 link-decore"><a
                        href="{% url 'detailed_movie' item.id %}">
                    <div class="card" style="height: 100%">
                        <div style="padding-top: 147%; position: relative; overflow: hidden">
                            <img src="{{ item.icon.url }}" class="card-img-top" style="position: absolute; top: 0"
                                 alt="{{ item.title }}">
                        </div>
                        <div class="card-body"
                             style=" display: flex; flex-direction: column; justify-content: space-between">
                            <div class="mb-1">
                                <h6 class="card-title">{{ item.title }}</h6>
                            </div>

                            <div style="align-self: flex-start">
                                <p><span class="stars">{{ item.rate }}</span></p>
                                <p>{{ item.rate|stringformat:'.1f' }}/10</p>
                            </div>
                        </div>
                    </div>
                </a>
                </div>
            {% endfor %}
        </div>
    </div>


    <h4 class="movie-detail">Comments</h4>
    <hr class="hr-class movie-detail">

    {% if user.is_authenticated %}
        <form method="post" action="{% url 'comment' movies.id %}">
            {% csrf_token %}
            <div class="card mt-2 movie-detail my-3">
                <div class="card-body">
                    <h5 class="card-title">{{ user.first_name }}</h5>
                    <textarea name="cm-text" style="width: 100%; height: 100px"
                              placeholder="Write your comment here"></textarea>
                    <input type="submit" value="Post" class="btn btn-primary">
                </div>
            </div>
        </form>
    {% endif %}
    {% if movies.comment_func %}
        {% for item in movies.comment_func %}
            <div class="card movie-detail mt-2 mb-2">
                <div class="card-header">
                    {{ item.author.first_name }}
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>{{ item.cm_text }}</p>
                        <footer class="blockquote-footer"><cite
                                title="Source Title">{{ item.cm_date|date:'d M Y, H:i' }}</cite>
                        </footer>
                    </blockquote>
                </div>
            </div>
        {% endfor %}

    {% endif %}

{% endblock %}

movies/templates/movies/search_result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .link-decore a:link {
            color: black;
        }

        .link-decore a:visited {
            color: black;
        }

        a:hover {
            color: black;
            text-decoration: none;
        }

        span.stars, span.stars span {
            display: block;
            background: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star-o-white.svg) 0 0 repeat-x;
            width: 120px; /* width of a star multiplied by 5 */
            height: 12px; /* the height of the star */
            background-size: 12px 12px;
            filter: drop-shadow(0px 0px 0px #444);
        }

        span.stars span {
            background-position: 0 0;
            background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star.svg);
        }
    </style>

    <div class="container mt-4">
        <h4 class="mt-4">Search result for {{ search_for }}</h4>
        <hr class="hr-class">
        <div>
            <div class="row">
                {% if search_results %}
                    {% for item in search_results %}
                        <div class="col-12 col-sm-6 col-md-4 col-lg-2 mb-3 link-decore"><a
                                href="{% url 'detailed_movie' item.id %}">
                            <div class="card" style="height: 100%">
                                <div style="padding-top: 147%; position: relative; overflow: hidden">
                                    <img src="{{ item.icon.url }}" class="card-img-top"
                                         style="position: absolute; top: 0"
                                         alt="{{ item.title }}">
                                </div>
                                <div class="card-body"
                                     style=" display: flex; flex-direction: column; justify-content: space-between">
                                    <div class="mb-1">
                                        <h6 class="card-title">{{ item.title }}</h6>
                                    </div>

                                    <div style="align-self: flex-start">
                                        <p><span class="stars">{{ item.rate }}</span></p>
                                        <p>{{ item.rate|stringformat:'.1f' }}/10</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="my-5 mx-auto text-center">
                        <h1 class="my-4">Oops!</h1>
                        <h3 class="my-4">Your search has no result, please search a movie name or part of it!</h3>
                        <button class="my-4 btn border-info btn-lg"><a style="text-decoration: none" href="{% url 'home' %}">Home</a></button>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}