TMDB/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('actors/', include('actress.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actress/urls.py
from django.urls import path
from actress import views

urlpatterns = [
    path('', views.ActorsListView.as_view(), name='actors'),
    path('<int:pk>/', views.DetailedActor.as_view(), name='actor_detail'),
]

actress/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Actor(models.Model):
    name = models.CharField(max_length=256)
    born_date = models.DateField()
    icon = models.ImageField(upload_to='images/')
    biography = models.TextField(null=True)

    def get_age(self):
        return timezone.now().year - self.born_date.year

    def brief_summary(self):
        return self.biography[:300] + '...'

    def __str__(self):
        return self.name

actress/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from actress import models
from movies.models import Movies


# Create your views here.
class ActorsListView(ListView):
    template_name = 'actress/all_actors.html'
    model = models.Actor
    paginate_by = 10

    def get_queryset(self):
        return models.Actor.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Actors'
        return context


class DetailedActor(DetailView):
    template_name = 'actress/detailed_actor.html'
    model = models.Actor

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.object.name
        return context

actress/templates/actress/all_actors.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>

        .link-decore a:link{
            color: black;
        }
        .link-decore a:visited{
            color: black;
        }
        a:hover{
            color: blue;
            text-decoration: none;
        }

        .blog-card {
            display: -webkit-box;
            display: flex;
            -webkit-box-orient: vertical;
            -webkit-box-direction: normal;
            flex-direction: column;
            box-shadow: 0 3px 7px -1px rgba(0, 0, 0, 0.1);
            margin: auto auto 1.6%;
            background: #fff;
            line-height: 1.4;
            font-family: sans-serif;
            border-radius: 5px;
            overflow: hidden;
            z-index: 0;
            width: 100%;
        }

        .blog-card a {
            color: inherit;
        }

        .blog-card a:hover {
            color: #4a30d6;
        }

        .blog-card:hover .photo {
            -webkit-transform: scale(1.3) rotate(3deg);
            transform: scale(1.3) rotate(3deg);
        }

        .blog-card .meta {
            position: relative;
            z-index: 0;
            height: 300px;
        }

        .blog-card .photo {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            object-fit: cover;
            background-size: cover;
            background-position: center;
            -webkit-transition: -webkit-transform .2s;
            transition: -webkit-transform .2s;
            transition: transform .2s;
            transition: transform .2s, -webkit-transform .2s;
        }

        .blog-card .details,
        .blog-card .details ul {
        {#margin: auto;#} padding: 0;
            list-style: none;
        }

        .blog-card .details {
            position: absolute;
            top: 0;
            bottom: 0;
            left: -100%;
            margin: auto;
            -webkit-transition: left .2s;
            transition: left .2s;
            background: rgba(0, 0, 0, 0.6);
            color: #fff;
            padding: 10px;
            width: 100%;
            font-size: .9rem;
        }

        .blog-card .details a {
            -webkit-text-decoration: dotted underline;
            text-decoration: dotted underline;
        }

        .blog-card .details ul li {
            display: inline-block;
        }

        .blog-card .details .author:before {
            font-family: FontAwesome;
            margin-right: 10px;
            content: "\f007";
        }

        .blog-card .details .date:before {
            font-family: FontAwesome;
            margin-right: 10px;
            content: "\f133";
        }

        .blog-card .details .tags ul:before {
            font-family: FontAwesome;
            content: "\f02b";
            margin-right: 10px;
        }

        .blog-card .details .tags li {
            margin-right: 2px;
        }

        .blog-card .details .tags li:first-child {
            margin-left: -4px;
        }

        .blog-card .description {
            padding: 1rem;
            background: #fff;
            position: relative;
            z-index: 1;
        }

        .blog-card .description h1,
        .blog-card .description h2 {
            font-family: Poppins, sans-serif;
        }

        .blog-card .description h1 {
            line-height: 1;
            margin: 0;
            font-size: 1.7rem;
        }

        .blog-card .description h2 {
            font-size: 1rem;
            font-weight: 300;
            text-transform: uppercase;
            color: #a2a2a2;
            margin-top: 5px;
        }

        .blog-card .description .read-more {
            text-align: right;
            {#margin-top: 20%;#}
        }

        .blog-card .description .read-more a {
            color: #4a72d6;
            display: inline-block;
            position: relative;
        }

        .blog-card .description .read-more a:after {
        {#content: "\f061";#} font-family: FontAwesome;
            margin-left: -10px;
            opacity: 0;
            vertical-align: middle;
            -webkit-transition: margin .3s, opacity .3s;
            transition: margin .3s, opacity .3s;
        }

        .blog-card .description .read-more a:hover:after {
            margin-left: 5px;
            opacity: 1;
        }

        .blog-card p {
            position: relative;
            margin: 1rem 0 0;
        }

        .blog-card p:first-of-type {
            margin-top: 1.25rem;
        }

        .blog-card p:first-of-type:before {
            content: "";
            position: absolute;
            height: 5px;
            background: #5ad67d;
            width: 35px;
            top: -0.75rem;
            border-radius: 3px;
        }

        .blog-card:hover .details {
            left: 0%;
        }

        @media (min-width: 992px) {
            .blog-card {
                -webkit-box-orient: horizontal;
                -webkit-box-direction: normal;
                flex-direction: row;
                max-width: 100%;
            }

            .blog-card .meta {
                flex-basis: 40%;

            }

            .blog-card .description {
                flex-basis: 60%;
            }

            .blog-card .description:before {
                -webkit-transform: skewX(-3deg);
                transform: skewX(-3deg);
                content: "";
                background: #fff;
                width: 30px;
                position: absolute;
                left: -10px;
                top: 0;
                bottom: 0;
                z-index: -1;
            }

            .blog-card.alt {
                -webkit-box-orient: horizontal;
                -webkit-box-direction: reverse;
                flex-direction: row-reverse;
            }

            .blog-card.alt .description:before {
                left: inherit;
                right: -10px;
                -webkit-transform: skew(3deg);
                transform: skew(3deg);
            }

            .blog-card.alt .details {
                padding-left: 25px;
            }
        }

    </style>

    <div class="container">
        <div class="row">
            {% for actor in actor_list %}
                <div class="blog-card mt-4">
                    <div class="meta">
                        <div class="photo"
                             style="background-image: url({{ actor.icon.url }});"></div>
                        <ul class="details">
                            <span>{{ actor.name }}</span>
                            <div>
                                <span>age: {{ actor.get_age }}</span>
                            </div>
                        </ul>
                    </div>
                    <div class="description">
                        <h1>{{ actor.name }}</h1>
                        <h2>Born Date: {{ actor.born_date|date:'d M Y' }}</h2>
                        <p>{{ actor.brief_summary }}</p>
                        <div style="align-self: flex-start" class="link-decor">
                            <p>Movies: {% for item in actor.actors_movies.all %}
                                {% if forloop.counter == actor.actors_movies.all|length %}
                                    <a href="{% url 'detailed_movie' item.movie.id %}">{{ item.movie.title }}</a>
                                {% else %}
                                    <a href="{% url 'detailed_movie' item.movie.id %}">{{ item.movie }}</a>,
                                {% endif %}
                            {% endfor %}
                            </p>
                        </div>
                        <p class="read-more">
                            <a href="{% url 'actor_detail' actor.id %}">Read More</a>
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                    <li class="page-item active"><a class="page-link"
                                                    href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>

{% endblock %}

actress/templates/actress/detailed_actor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>
        .link-decore a:link{
            color: black;
        }
        .link-decore a:visited{
            color: black;
        }
        a:hover{
            color: black;
            text-decoration: none;
        }
        span.stars, span.stars span {
            display: block;
            background: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star-o-white.svg) 0 0 repeat-x;
            width: 120px; /* width of a star multiplied by 5 */
            height: 12px; /* the height of the star */
            background-size: 12px 12px;
            filter: drop-shadow(0px 0px 0px #444);
        }

        span.stars span {
            background-position: 0 0;
            background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star.svg);
        }
        .card-horizontal {
            display: flex;
            flex: 1 1 auto;
        }
    </style>

    <div class="container mb-4">
        <div class="row">
                <div class="col-12 mt-3">
                <div class="card">
                    <div class="card-horizontal">
                        <div class="img-square-wrapper">
                            <img class="" src="{{ actor.icon.url }}" alt="Card image cap">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">{{ actor.name }}</h4>
                            <small class="text-muted">Born on: {{ actor.born_date|date:'d M Y' }}</small>
                            <p class="card-text"><span class="font-italic text-primary">Mini Biography:</span> {{ actor.biography }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <h4 class="mt-4">Actor Movie's</h4>
        <hr class="hr-class">

        <div>
            <div class="row">
                {% for item in actor.actors_movies.all %}
                    <div class="col-12 col-sm-6 col-md-4 col-lg-2 mb-3 link-decore"><a href="{% url 'detailed_movie' item.movie.id %}">
                        <div class="card" style="height: 100%">
                            <div style="padding-top: 147%; position: relative; overflow: hidden">
                                <img src="{{ item.movie.icon.url }}" class="card-img-top" style="position: absolute; top: 0"
                                     alt="{{ item.movie.title }}">
                            </div>
                            <div class="card-body"
                                 style=" display: flex; flex-direction: column; justify-content: space-between">
                                <div class="mb-1">
                                    <h6 class="card-title">{{ item.movie.title }}</h6>
                                </div>

                                <div style="align-self: flex-start">
                                    <p><span class="stars">{{ item.movie.rate }}</span></p>
                                    <p>{{ item.movie.rate }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>

{% endblock %}