TMDB/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('actors/', include('actress.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('contact/', views.contact_us, name='contact'),
    path('thanks/', views.submit_message, name='messagesent'),
    path('<int:pk>/watchlist', views.add_watch_list, name='watchlist'),
    path('watchlist/', views.watch_list_func, name='watchlist_func'),
    path('<int:pk>/delete/', views.delete_watch_list, name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib import auth
from movies.models import Movies
from django.conf import settings


# Create your models here.
class User(auth.models.User, PermissionsMixin):
    watch_list = models.ManyToManyField(Movies, blank=True)

    def __str__(self):
        return f'{self.username}'


class UserWatchList(models.Model):
    movie_added_to_list = models.ForeignKey(Movies, on_delete=models.CASCADE,
                                            related_name='movie_on_list')
    user_who_add_to_list = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_added', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user_who_add_to_list) + ' - ' + str(self.movie_added_to_list)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import auth
from django.core.mail import BadHeaderError, send_mail, EmailMultiAlternatives, EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from movies.models import Movies
from accounts.models import UserWatchList
from django.contrib.auth.views import login_required


# Create your views here.
def signup(request):
    error = {}
    page_title = 'Sign Up'
    if request.method == 'POST':
        if request.POST['password'] == request.POST['confirm_password']:
            try:
                user = User.objects.get(email=request.POST['email'])
                error["email"] = "Already taken"
                return render(request, 'accounts/signup.html', {'error': error, 'page_title': page_title})
            except User.DoesNotExist:
                user = User.objects.create_user(username=request.POST['email'], password=request.POST['password'],
                                                email=request.POST['email'])
                user.first_name = request.POST['firstname']
                user.save()
                auth.login(request, user)
                return redirect('home')
        else:
            error['password'] = 'Passwords does not match'
            return render(request, 'accounts/signup.html', {'error': error, 'page_title': page_title})
    else:
        return render(request, 'accounts/signup.html', {'page_title': page_title})


def login(request):
    error = {}
    page_title = 'Login'
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['email'], password=request.POST['password'])
        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            error["auth_user"] = "Username or Password does not correct"
            return render(request, 'accounts/login.html', {'error': error, 'page_title': page_title})
    else:
        return render(request, 'accounts/login.html', {'page_title': page_title})


def contact_us(request):
    return render(request, 'accounts/contact.html', {'page_title': 'Contact us'})


def submit_message(request):
    if request.method == 'POST':
        subject = request.POST.get('subject', '')
        message = request.POST.get('message', '')
        from_email = 'towhid.lyft@gmail.com'
        headers = {'Reply-To': request.user.email}
        if subject and message and from_email:
            try:
                msg = EmailMessage(subject, message, from_email, ['towhid.savari@gmail.com'], headers=headers)
                msg.send()

            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return render(request, 'accounts/thanks_page.html', {'page_title': 'Thanks'})
        else:
            # In reality we'd use a form class
            # to get proper validation errors.
            return HttpResponse('Make sure all fields are entered and valid.')


def add_watch_list(request, pk):
    if request.method == 'POST':
        movie_item = get_object_or_404(Movies, pk=pk)
        print(movie_item)
        user_item = User(pk=request.user.pk)
        print(user_item)
        user_list = UserWatchList()
        user_list.movie_added_to_list = movie_item
        user_list.user_who_add_to_list = user_item
        user_list.save()
        return redirect('/movies/' + str(pk))


@login_required
def watch_list_func(request):
    user_watch_list = Movies.objects.filter(movie_on_list__user_who_add_to_list_id=request.user.pk)
    return render(request, 'accounts/watch_list.html', {'user_watch_list': user_watch_list,
                                                        'page_title': request.user.first_name + '\'s Watchlist'})


def delete_watch_list(request, pk):
    UserWatchList.objects.filter(movie_added_to_list_id=pk,
                                 user_who_add_to_list_id=request.user.pk).delete()
    return redirect('accounts:watchlist_func')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .error {
            border: 1px solid #ff3749;
        }
    </style>

    <div class="container">
        <form method="post" action="{% url 'accounts:login' %}" class="mt-4" style="margin: auto; max-width: 30%">
            {% csrf_token %}
            <h2>Log In</h2>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
                    <input type="email" class="form-control {% if error.auth_user %}{{ 'error' }}{% endif %}" name="email" placeholder="Email Address"
                           required="required">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    <input id="id_password1" type="password" class="form-control {% if error.auth_user %}{{ 'error' }}{% endif %}" name="password" placeholder="Password"
                           required="required">
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block btn-lg">Sign In</button>
            </div>
        </form>
        <div class="text-center my-5">Don't have an account? <a href="{% url 'accounts:signup' %}">Sign Up here</a></div>
        </form>
    </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <style>
        .error {
            border: 1px solid #ff3749;
        }
    </style>

    <div class="signup-form mt-4 my-5 text-center col-lg-8" style="margin:auto; max-width: 30%">
        <form action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
            <h2>Create Account</h2>
            <p class="lead">It's free and hardly takes more than 30 seconds.</p>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
                    <input id="id_firstname" type="text" class="form-control {% if error.email %}{{ 'error' }}{% endif %}"
                           name="firstname" placeholder="Your name"
                           required="required">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
                    <input id="id_email" type="email" class="form-control {% if error.email %}{{ 'error' }}{% endif %}"
                           name="email" placeholder="Email Address"
                           required="required">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    <input id="id_password1" type="password" class="form-control {% if error.password %}{{ 'error' }}{% endif %}" name="password" placeholder="Password"
                           required="required">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
				<span class="input-group-addon">
					<i class="fa fa-lock"></i>
					<i class="fa fa-check"></i>
				</span>
                    <input id="id_password2" type="password" class="form-control {% if error.password %}{{ 'error' }}{% endif %}" name="confirm_password"
                           placeholder="Confirm Password"
                           required="required">
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block btn-lg">Sign Up</button>
            </div>
            <p class="small text-center">By Sign Up button, you agree to our <br><a href="#">Terms &amp;
                Conditions</a>, and <a href="#">Privacy Policy</a>.</p>
        </form>
        <div class="text-center">Already have an account? <a href="{% url 'accounts:login' %}">Login here</a></div>
    </div>

{% endblock %}

accounts/templates/accounts/thanks_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container border my-5 border-success rounded py-4 text-center" style="width: 100%; min-height: 400px%">
        <h2>Thanks, I'll be in touch with you, shortly</h2>
        <button class="my-5 btn border-info btn-lg"><a style="text-decoration: none" href="{% url 'home' %}">Home</a></button>
    </div>

{% endblock %}

accounts/templates/accounts/watch_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>
        .link-decore a:link{
            color: black;
        }
        .link-decore a:visited{
            color: black;
        }
        a:hover{
            color: black;
            text-decoration: none;
        }

        span.stars, span.stars span {
            display: block;
            background: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star-o-white.svg) 0 0 repeat-x;
            width: 120px; /* width of a star multiplied by 5 */
            height: 12px; /* the height of the star */
            background-size: 12px 12px;
            filter: drop-shadow(0px 0px 0px #444);
        }

        span.stars span {
            background-position: 0 0;
            background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/747/star.svg);
        }
    </style>

    <div class="container mt-4">
        <h4 class="mt-4">Your Watch List</h4>
        <hr class="hr-class">
        <div>
            <div class="row">
                {% if user_watch_list %}
                    {% for item in user_watch_list.all %}
                    <div class="col-12 col-sm-6 col-md-4 col-lg-2 mb-3 link-decore"><a href="{% url 'detailed_movie' item.id %}">
                        <div class="card" style="height: 100%">
                            <div style="padding-top: 147%; position: relative; overflow: hidden">
                                <img src="{{ item.icon.url }}" class="card-img-top" style="position: absolute; top: 0"
                                     alt="{{ item.title }}">
                            </div>
                            <div class="card-body"
                                 style=" display: flex; flex-direction: column; justify-content: space-between">
                                <div class="mb-1">
                                    <h6 class="card-title">{{ item.title }}</h6>
                                </div>

                                <div style="align-self: flex-start">
                                    <p><span class="stars">{{ item.rate }}</span></p>
                                    <p>{{ item.rate|stringformat:'.1f' }}/10</p>
                                    <form method="post" action="{% url 'accounts:delete' item.id %}">
                                        {% csrf_token %}
                                        <input type="submit" value="Watched!" class="btn btn-danger float-right btn-sm" style="width: 100%">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </a>
                    </div>
                {% endfor %}
                {% else %}
                    <div class="my-5 mx-auto text-center">
                        <h1 class="my-4">Oops!</h1>
                        <h3 class="my-4">You don't have any movies in your watch list,
                        go to movies page and select ones you want to watch later!</h3>
                        <button class="my-4 btn border-info btn-lg"><a style="text-decoration: none" href="{% url 'home' %}">Home</a></button>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}